.gitignore

Ignore temp log files like `dubbo-governance.log.1`.

Ignore temp log files like `dubbo-governance.log.1`

---

dubbo-admin-frontend/src/components/AccessControl.vue
dubbo-admin-frontend/src/components/AceEditor.vue

If configurations use object, change object property value will not trigger `watch` event, separate each configuration item to fix this problem.

Separate each configuration item

---

dubbo-admin-backend/pom.xml
pom.xml

* Exclude dependency `netty:3.x` for dubbo and curator-framework
* Add dependency `netty-all:4.1.30.Final`

[#141] Fix warning on startup with dubbo2.6.4

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/controller/ServiceController.java

If there is no `method = RequestMethod.GET`, it will accept all methods and Swagger will show all methods api.

Only accept the GET method

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/handler/CustomExceptionHandler.java

Should return `HttpStatus.BAD_REQUEST` for bad parameter requests.
```
http 127.0.0.1:8080/api/dev/service
HTTP/1.1 500
Connection: close
Content-Type: application/json;charset=UTF-8
Date: Tue, 01 Jan 2019 06:00:51 GMT
Transfer-Encoding: chunked
{
"message": "System Error, please try again later! Message:Required String parameter 'pattern' is not present",
"success": false
}
```
should be
```
http 127.0.0.1:8080/api/dev/service
HTTP/1.1 400
Connection: close
Content-Type: application/json;charset=UTF-8
Date: Tue, 01 Jan 2019 06:01:27 GMT
Transfer-Encoding: chunked
{
"message": "Parameter validation failure! Message:Required String parameter 'pattern' is not present",
"success": false
}
```

Return BAD_REQUEST for parameter error

---

dubbo-admin-backend/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.data.config.GovernanceConfiguration
dubbo-admin-backend/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.data.metadata.MetaDataCollector
dubbo-admin-backend/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration
dubbo-admin-backend/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.metadata.MetaDataCollector

fix no such extension after refactor
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dubbo.admin.registry.config.GovernanceConfiguration]: Factory method 'getDynamicConfiguration' threw exception; nested exceptio
n is java.lang.IllegalStateException: No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name zookeeper
```
please start backend server to check this

Fix no such extension

---

dubbo-admin-backend/pom.xml
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/registry/config/impl/ZookeeperConfiguration.java
dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/registry/config/impl/ZookeeperConfigurationTest.java
pom.xml

- Add null parameter check for `key` and `path`
- Return false if exception thrown in `zkClient.delete().forPath(path);`
- Remove unused import which may introduce compile warning `import java.security.acl.Group;`
- Add unit test for ZookeeperConfiguration #216

Tweak ZookeeperConfiguration

---

dubbo-admin-ui/src/components/ServiceSearch.vue
dubbo-admin-ui/src/components/test/ServiceTest.vue
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js

Modifications:
- Add links to **Service Test** in Service List
- Using autocomplete input component to give suggestions to users and support fuzzy search
Related issue: #285

feature: navigation between services and tests. Fixes #285

---

dubbo-admin-ui/src/components/test/TestMethod.vue

https://github.com/apache/incubator-dubbo-admin/blob/1faaec0b747604897c4a9af6c67222744231ecd7/dubbo-admin-ui/src/components/test/TestMethod.vue#L131
resolves #347 
When testing no-arg method, the `parametersTypes` is empty, and spliting an empty string `""` generates an array of `[""]`, resulting issue #347

[DUBBO-ADMIN-347] Fix bug when testing no-arg method

---

dubbo-admin-ui/src/components/public/JsonEditor.vue

方法测试页面编辑器模式选择 “code” 时，编辑器样式错位 https://github.com/apache/dubbo-admin/issues/358

ace 行号栏 z-index 过高 #358

---

dubbo-admin-ui/src/components/metrics/ServiceMetrics.vue

Clear timer when an error occurs in the search on the Metrics page.
If not cleared, the error will always be prompted

fix metrics search error, clear timer

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/GenericServiceImpl.java

在调用genericService的invoke之前，擦出掉范型。fix https://github.com/apache/dubbo-admin/issues/362

在调用genericService的invoke之前，擦出掉范型。fix #362

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/ConsulConfiguration.java
dubbo-admin-server/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration

When using Dubbo, I use consul for service discovery, but I found that only the support of consul metadata collection is available in Dubbo admin, so I added the support for consul service discovery. Local test is right, but I'm not sure if I need to change it.

support consul

---

README.md
README_ZH.md

Test case contain code for various registries that will cause the test to fail and therefore cannot be packaged.

fix problem in README.md and README_ZH.md

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/ApiDocsDubboGenericUtil.java
dubbo-admin-ui/package-lock.json
dubbo-admin-ui/src/components/apiDocs/ApiDocs.vue
dubbo-admin-ui/src/components/apiDocs/ApiForm.vue

#743 
1. Dubbo Admin can load api docs list
2. Dubbo Admin can load api information
1. Set dubbo ReferenceConfig `org.apache.dubbo.apidocs.core.providers.IDubboDocProvider` 
version=apiDocsGroup & group=v1
2. ApiDocs.vue&ApiForm.vue pass paramsDesc to Dubbo Admin Server.
Dubbo Admin Verison : 0.3.0-SNAPSHOT
Dubbo API Docs Version: 2.7.8.3-SNAPSHOT

support feature multi-overload methods of the same method name #743

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java

删除服务级别的条件路由，实际并没有删除掉zk中provider/routers/下的内容 
原因：添加的dubbo url路径带version，而删除的dubbo url没有version
XX
XXXX

fix bug of delete service route

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RegistryServerSync.java

[Fix bug](#908)

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/ZookeeperMetaDataCollector.java

1. ZookeeperMetaDataCollector#init() add digest authorization support. If not set, can be throw NoAuth Exception when use instance discovery and zk node set acl

ZookeeperMetaDataCollector init method add zk digest acl support

---

NOTICE
dubbo-admin-distribution/src/NOTICE
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/SwaggerConfiguration.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/Entity.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/Provider.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/RegistrySource.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/AdminMappingListener.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/NacosMetaDataCollector.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/ConsumerServiceImpl.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/InstanceRegistryCache.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/InstanceRegistryQueryHelper.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/ProviderServiceImpl.java
dubbo-admin-ui/src/components/ServiceDetail.vue
dubbo-admin-ui/src/components/public/Footers.vue
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js

Fix notice and opt registry source

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-ui/src/components/ServiceDetail.vue
dubbo-admin-ui/src/router/index.js

Fix 服务测试模块内的方法测试执行后，动态生成consumer信息，host为空时，控制台和服务'消费者'标签无法显示问题
