README.md

add description for how to use it

add description for how to use it

---

dubbo-admin/src/main/resources/application.properties
dubbo-admin/src/main/resources/dubbo-admin.xml

remove hard code. so we can use env `dubbo.registry.address` to modify registry url

remove hard code for registry url

---

dubbo-admin/src/main/resources/i18n/message_en.properties
dubbo-admin/src/main/resources/i18n/message_zh.properties
dubbo-admin/src/main/resources/i18n/message_zh_TW.properties

Add i18n mapping #55

---

dubbo-monitor-simple/pom.xml
dubbo-monitor-simple/src/main/resources/META-INF/assembly/bin/start.sh
dubbo-monitor-simple/src/main/resources/META-INF/dubbo/internal/com.alibaba.dubbo.container.Container
dubbo-monitor-simple/src/main/resources/conf/dubbo.properties

#3 
Fix bugs: 
1. class no found for servlet; 
2. no applications, services... menu entries; 
3. no log output. 
Enhance start script:
enhance script start.sh

Fix bugs: class no found for servlet; no applications, services... menu entries; no log output. enhance script start.sh

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/controller/AccessesController.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/dto/BaseDTO.java
dubbo-admin-frontend/src/components/AccessControl.vue

- Add BaseDTO for receive ID parameter with @RequestBody.
- Add detail api.
- Change `search` to GET method.
- Change `delete` parameter use BaseDTO.

DTO restructure

---

dubbo-admin-frontend/src/components/AceEditor.vue

Fix AceEditor if value change cursor goes to end.
Add config `overrideValueHistory`(boolean)
- true = `$ace.getSession().setValue(newVal)` // This will set value and reset undo history
- false = `$ace.setValue(newVal, 1)`

Fix AceEditor if value change cursor goes to end

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/controller/AccessesController.java
dubbo-admin-frontend/src/components/governance/AccessControl.vue
dubbo-admin-frontend/src/components/http-common.js

Examples: https://restfulapi.net/rest-api-design-tutorial-with-example/

Change API to restful

---

dubbo-admin-frontend/src/components/governance/AccessControl.vue

When the search button is clicked and nothing is entered, the full amount of data is searched.

Do not need to load a full amount of data by default.

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/config/I18nConfig.java
dubbo-admin-backend/src/main/resources/application-develop.properties
dubbo-admin-backend/src/main/resources/application-production.properties
pom.xml

Add environment difference and CORS setting

Add environment difference and CORS setting

---

dubbo-admin-frontend/src/components/governance/AccessControl.vue
dubbo-admin-frontend/src/components/public/notify/Snackbar.vue
dubbo-admin-frontend/src/components/public/notify/index.js
dubbo-admin-frontend/src/main.js

main.js
```javascript
import Notify from './components/public/notify'
Vue.use(Notify)
```
usage
```
this.$notify(message, color)
this.$notify.error(message)
this.$notify.success(message)
this.$notify.info(message)
```

Add notify plugin

---

README.md
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/common/CommonResponse.java
dubbo-admin-frontend/src/components/http-common.js

Update CommonResponse and frontend error handing.

frontend error handing #152

---

dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/governance/util/UrlUtilsTest.java
pom.xml

upgrade jacoco version to support jdk11

upgrade jacoco version to support jdk11

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/config/I18nConfig.java
dubbo-admin-frontend/config/index.js
dubbo-admin-frontend/src/components/ServiceDetail.vue
dubbo-admin-frontend/src/components/ServiceSearch.vue
dubbo-admin-frontend/src/components/governance/AccessControl.vue
dubbo-admin-frontend/src/components/governance/LoadBalance.vue
dubbo-admin-frontend/src/components/governance/Overrides.vue
dubbo-admin-frontend/src/components/governance/RoutingRule.vue
dubbo-admin-frontend/src/components/governance/WeightAdjust.vue
dubbo-admin-frontend/src/components/http-common.js
dubbo-admin-frontend/src/main.js

* Remove backend CORS
* Add frontend proxy
* Add axios to global

Change to frontend proxy

---

dubbo-admin-frontend/src/components/ServiceSearch.vue

Bind enter press event on search input box

Bind press keyboard event on search input box

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/common/util/MD5Util.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/data/config/impl/ZookeeperConfiguration.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/data/metadata/impl/ZookeeperMetaDataCollector.java

using logging framework instead of `e.printStack()` to console
About logging, I noticed that there are very few logs in our controller/service.
I think it's better to add some trace log.

Optimize logging

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/common/util/Constants.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/service/RegistryServerSync.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/service/impl/ProviderServiceImpl.java

An exception occurs when search filter start with [? + *]

one search bug fix & format some code

---

dubbo-admin-frontend/src/components/ServiceDetail.vue
dubbo-admin-frontend/src/components/ServiceSearch.vue
dubbo-admin-frontend/src/components/governance/AccessControl.vue
dubbo-admin-frontend/src/components/governance/LoadBalance.vue
dubbo-admin-frontend/src/components/governance/Overrides.vue
dubbo-admin-frontend/src/components/governance/RoutingRule.vue
dubbo-admin-frontend/src/components/governance/TagRule.vue
dubbo-admin-frontend/src/components/governance/WeightAdjust.vue

fix issues#250

---

dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java
dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/controller/ManagementControllerTest.java
dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/controller/ServiceControllerTest.java

This patch add more integration tests, mainly test upon `org.apache.dubbo.admin.controller.ConditionRoutesController`

add more integration tests

---

dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/config/ConfigCenterTest.java
dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java

Add missing license announcement

Add missing license announcement

---

.travis.yml
dubbo-admin-backend/src/test/java/org/apache/dubbo/admin/controller/ServiceControllerTest.java
google_checks.xml
pom.xml

related issue #272 
This patch introduces checkstyle plugin to unify code style, for now it only introduces the plugin and didn't adjusts existed code to accord the style, checking whether *travis-ci* works well with this

introduce checkstyle plugin to unify code style

---

dubbo-admin-frontend/src/components/ServiceSearch.vue
dubbo-admin-frontend/src/components/governance/AccessControl.vue
dubbo-admin-frontend/src/components/governance/LoadBalance.vue
dubbo-admin-frontend/src/components/governance/Overrides.vue
dubbo-admin-frontend/src/components/governance/RoutingRule.vue
dubbo-admin-frontend/src/components/governance/WeightAdjust.vue
dubbo-admin-frontend/src/store/index.js

Add input prompt function for all search page, except tag rule page.
PS: I noticed that the author has already designed a search box component. But it is not fully finished yet. When you are finished, I can help extract the common code to simplify the prompt function code.

Add input prompt function for all search page

---

dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/common/util/ServiceTestUtil.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/controller/ServiceTestController.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/model/domain/MethodMetadata.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/model/dto/ServiceTestDTO.java
dubbo-admin-backend/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/ZookeeperMetaDataCollector.java
dubbo-admin-backend/src/main/resources/application.properties
dubbo-admin-frontend/src/components/public/JsonEditor.vue
dubbo-admin-frontend/src/components/public/Search.vue
dubbo-admin-frontend/src/components/test/ServiceTest.vue
dubbo-admin-frontend/src/components/test/TestMethod.vue

This patch supports more types of method tests(mainly in complex method arguments) and do some cleanup works and minor refactor.

test service's parameterized methods

---

dubbo-admin-server/pom.xml
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/DubboAdminApplication.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ServiceController.java
dubbo-admin-ui/src/components/ServiceSearch.vue

server-side pagination. resolve #318

[DUBBO-OPS-318]: Feature: server-side pagination. resolve issue #318

---

dubbo-admin-distribution/src/LICENSE
dubbo-admin-distribution/src/licenses/LICENSE-lodash
dubbo-admin-server/pom.xml
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/GenericServiceImpl.java
dubbo-admin-ui/package.json
dubbo-admin-ui/src/components/test/TestMethod.vue
dubbo-admin-ui/src/util/index.js
pom.xml

bugfix: test parameter type conversion. resolve #328

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/RouteUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java
dubbo-admin-ui/src/components/governance/RoutingRule.vue

Fix issue#385:change zk path of router config

---

docker/0.1.0/Dockerfile
docker/0.2.0/Dockerfile
docker/stack.yml

Close #356 
Repo is ready: https://hub.docker.com/r/apache/dubbo-admin

Add dockerfile for dockerhub autobuild

---

pom.xml

[Dubbo-421] Update dubbo version to 2.7.3-SNAPSHOT

---

dubbo-admin-ui/src/components/ServiceDetail.vue

https://github.com/apache/dubbo-admin/issues/130

add 'weight' label to provider list #130

---

dubbo-admin-ui/src/components/test/ServiceTest.vue

1. The service test page will throw undefined exception in console if the "service" parameter in url is null.
2. Keep the style of service test page consistent with other pages

Fix some UI bug on test module

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/ProviderServiceImpl.java

IP地址检索添加*查询。
已知问题：
底层使用java的pattern。WEB层输入的.无法真确在底层解析。

IP地址检索服务支持*模糊查询

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/RedisMetaDataCollector.java

 redis metadata support cluster #480

---

dubbo-admin-server/pom.xml
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/ConsulMetaDataCollector.java
dubbo-admin-server/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.metadata.MetaDataCollector
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/registry/metadata/impl/ConsulMetaDataCollectorTest.java
pom.xml

support consul metadata center implementation #406

 Consul metadata center

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java
dubbo-admin-server/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration

add support for nacos configuration center

nacos dynamic configuration center support

---

dubbo-admin-ui/src/components/test/TestMethod.vue

using this.$axios instead of axios

---

pom.xml

Update dependency version of fastjson for security reason
https://help.aliyun.com/noticelist/articleid/1060253179.html

Update dependency version of fastjson

---

docker/0.1.0/Dockerfile
docker/0.2.0/Dockerfile

close https://github.com/apache/dubbo-admin/issues/601

fix dockerfile

---

dubbo-admin-server/src/main/resources/META-INF/spring-configuration-metadata.json

close https://github.com/apache/dubbo-admin/issues/562
refer https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor

add spring-configuration-metadata.json 

---

.github/workflows/ci.yml
dubbo-admin-server/src/main/resources/application-test.properties
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/AbstractSpringIntegrationTest.java

[WIP] use random zookeeper port in unit test

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/MetricsCollectController.java

change MetricsCollectController autowiring mode

change to constructor autowiring mode

---

.github/workflows/integration.yml
dubbo-admin-test/pom.xml
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/ConsumerBootstrap.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/ProviderBootstrap.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/consumer/AnnotatedGreetingService.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/consumer/RestApiService.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/provider/AnnotatedGreetingService.java
dubbo-admin-test/src/main/resources/spring/dubbo-consumer.properties
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/BaseIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/LoginIT.java

+ add consumer
+ include in integration test
+ add screenshot capture

add consumer for integration test

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/Constants.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java
dubbo-admin-server/src/main/resources/application.properties

#591 add namespace for nacos
#628 dubbo-admin 使用nacos做注册中心 无法查询到服务

#591 add namespace for nacos

---

NOTICE
dubbo-admin-distribution/pom.xml
dubbo-admin-distribution/src/NOTICE
dubbo-admin-distribution/src/assembly/bin-release.xml
dubbo-admin-distribution/src/bin/config/application.properties
dubbo-admin-distribution/src/bin/shutdown.cmd
dubbo-admin-distribution/src/bin/shutdown.sh
dubbo-admin-distribution/src/bin/startup.cmd
dubbo-admin-distribution/src/bin/startup.sh
dubbo-admin-server/pom.xml

fix #677 dubbo admin 修改打包结构,增加启动脚本

---

dubbo-admin-ui/pom.xml
pom.xml

修复mvn install时前端编译报错问题

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/interceptor/AuthInterceptor.java
dubbo-admin-ui/src/components/http-common.js
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js
dubbo-admin-ui/src/main.js
dubbo-admin-ui/vue.config.js

- Navigate to login page When auth token failed.
- Fixes #682
- dubbo-admin-server token valid time 15min to 60min.

#682 fixed

---

.gitignore
docker/latest/Dockerfile
dubbo-admin-distribution/pom.xml
dubbo-admin-server/pom.xml
dubbo-admin-test/pom.xml
dubbo-admin-ui/package.json
dubbo-admin-ui/pom.xml
pom.xml

* 升级版本号为 0.3.0-SNAPSHOT,
* 版本号改为 ${revision}
* 修改groupId 为 org.apache.dubbo

升级版本号为 0.3.0-SNAPSHOT

---

dubbo-admin-ui/src/components/apiDocs/ApiForm.vue
dubbo-admin-ui/src/components/apiDocs/ApiFormItem.vue

#686 之前修复逻辑有问题,重新修复

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/interceptor/AuthInterceptor.java

- prevent NullPointerException on AuthInterceptor
- make session timeout configurable

prevent NullPointerException on AuthInterceptor

---

.github/ISSUE_TEMPLATE/dubbo-admin-feature-request-template.md

add feature request template

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/UserController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/interceptor/AuthInterceptor.java
dubbo-admin-server/src/main/resources/application.properties
dubbo-admin-ui/src/Login.vue
dubbo-admin-ui/src/components/http-common.js
dubbo-admin-ui/src/main.js

1. 增加server端用户token失效时间的配置
2. 修复根路径/路由校验失效的问题
3. 优化登录后redirect无效问题
4. 优化登录态失效后的体验，跳转登录页

易用性方面的一点优化

---

dubbo-admin-ui/src/components/metrics/ServiceMetrics.vue

基于ip过滤的metrics路径问题

---

.codecov.yml
.github/workflows/ci.yml
.github/workflows/integration.yml
README.md
README_ZH.md
docker/latest/Dockerfile
docker/latest/entrypoint.sh
dubbo-admin-server/src/main/resources/application-test.properties
dubbo-admin-server/src/main/resources/application.properties
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/utils/LocalDateTimeUtilTest.java
dubbo-admin-test/pom.xml
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/BaseIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/LoginIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/ManageIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/MetricIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/ServiceIT.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/pages/BasePage.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/pages/LoginPage.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/pages/ManagePage.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/pages/MetricRelationPage.java
dubbo-admin-test/src/test/java/org/apache/dubbo/admin/pages/ServicePage.java
dubbo-admin-ui/src/components/test/TestMethod.vue

+ enhance integration tests to cal test coverage (spilt them into unit and integration in codecov report)
+ add basic IT test

Add more tests for zookeeper registry

---

dubbo-admin-ui/src/components/http-common.js

* fix #697 bug.

---

dubbo-admin/src/main/java/com/alibaba/dubboadmin/web/mvc/RouterController.java
dubbo-admin/src/main/resources/templates/governance/screen/consumers/index.vm
dubbo-admin/src/main/resources/templates/governance/screen/providers/index.vm
dubbo-admin/src/main/resources/templates/governance/screen/services/index.vm

fix 404 and 500 when there are grouped services

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/Constants.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ConvertUtil.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ConditionRoutesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/BaseDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RouteService.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/consumer/AnnotatedGreetingService.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/provider/AnnotatedGreetingService.java
dubbo-admin-ui/package-lock.json
dubbo-admin-ui/src/components/ServiceSearch.vue
dubbo-admin-ui/src/components/governance/RoutingRule.vue
dubbo-admin-ui/src/components/metrics/ServiceMetrics.vue
dubbo-admin-ui/src/components/public/Breadcrumb.vue
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js

Fix and optimize some problems of conditional routing when using ZK to make it work
* Conditional routing adds version and group query conditions and form items in the case of service
* Modify the path saved to ZK by conditional route
Add a conditional route and verify that the condition works

Fix and optimize some problems of conditional routing when using ZK to make it work

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ApiDocsController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/docs/CallDubboServiceRequest.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/ApiDocsDubboGenericUtil.java
dubbo-admin-ui/src/components/apiDocs/ApiDocs.vue
dubbo-admin-ui/src/components/apiDocs/ApiForm.vue
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js

fix https://github.com/apache/dubbo-spi-extensions/issues/19 of api docs bug 
Group display is added in UI, and group parameter processing is added in interface call
Add group attribute in Dubbo annotation, you can see the interface group in the interface document module of dubbo admin and call the interface successfully

fix #19 of api docs bug 

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/NacosMetaDataCollector.java
pom.xml

[ISSUE #708]Nacos support auth

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/Constants.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ConvertUtil.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ApiDocsController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ConditionRoutesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/BaseDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/docs/CallDubboServiceRequest.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/NacosMetaDataCollector.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RouteService.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/ApiDocsDubboGenericUtil.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/consumer/AnnotatedGreetingService.java
dubbo-admin-test/src/main/java/org/apache/dubbo/admin/impl/provider/AnnotatedGreetingService.java
dubbo-admin-ui/package-lock.json
dubbo-admin-ui/src/components/ServiceSearch.vue
dubbo-admin-ui/src/components/apiDocs/ApiDocs.vue
dubbo-admin-ui/src/components/apiDocs/ApiForm.vue
dubbo-admin-ui/src/components/governance/RoutingRule.vue
dubbo-admin-ui/src/components/metrics/ServiceMetrics.vue
dubbo-admin-ui/src/components/public/Breadcrumb.vue
dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js
pom.xml

Merge the latest code into the antd branch
XX
XXXX

[2021-3-21]Merge the latest code into the antd branch

---

dubbo-admin-ui-antd/config/config.ts
dubbo-admin-ui-antd/config/routes.ts
dubbo-admin-ui-antd/src/app.tsx
dubbo-admin-ui-antd/src/pages/Service/index.tsx
dubbo-admin-ui-antd/src/pages/User/login/index.tsx
dubbo-admin-ui-antd/src/storage/auth.ts
dubbo-admin-ui/package-lock.json
dubbo-admin-ui/src/util/auth.js

* fixed login error.
* client token、username add to auth.ts file.
* add service module routes.
* modifed fetch userinfo error when page is not user.

Upstream dev change ui2antd

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ConvertUtil.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ConditionRoutesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/BaseDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/ConditionRouteDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/ConditionRouteResultDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RouteService.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/AccessesControllerTest.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java
dubbo-admin-ui/src/components/governance/RoutingRule.vue

fix condition query problem
1. `BaseDTO` remove service
2. fix condition query problem
XX
XXXX

Fix route rule some problem

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java

[ISSUE #716]Fix nacos dataId can't match dubbo

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ConvertUtil.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ConditionRoutesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/dto/ConditionRouteResultDTO.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/NacosConfiguration.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RouteService.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/AccessesControllerTest.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java
dubbo-admin-ui/src/components/apiDocs/ApiDocs.vue
dubbo-admin-ui/src/components/governance/RoutingRule.vue

Merge the latest code into the antd branch

Merge the latest code into the antd branch

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/ApiDocsDubboGenericUtil.java

Fix possible null pointer exception in ApiDocsDubboGenericUtil#invoke
XX
XXXX

Fix possible null pointer exception in ApiDocsDubboGenericUtil#invoke

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ServiceController.java

Fix #727
When registered dubbo version is under 2.7, the metadata returned by 'providerService.getProviderMetaData' method will represent as IP address, like 10.0.0.1. So the Json conversion will fail and throw internal server exception
XX
XXXX

[ISSUE #727] Fix possible JsonParseException exception in ServiceController

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ApiDocsController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/utils/ApiDocsDubboGenericUtil.java

Fix aip docs null ex

---

dubbo-admin-ui/src/lang/en.js
dubbo-admin-ui/src/lang/zh.js

The search function for test module actually do not support fuzzy search. The hint dose not correspond the reality.
XX
XXXX

Update test module hint

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/metadata/impl/RedisMetaDataCollector.java

#741 
fix：修复redis连接加入database参数问题
fix：修复redis获取元信息获取不到问题

修复redis连接加入database参数问题

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ApiDocsController.java

Adapt to the dubbo-api-docs-core-2.7.8.3.

---

docker/latest/Dockerfile
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/AccessesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ConditionRoutesController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/ConsumerService.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/ConsumerServiceImpl.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/AccessesControllerTest.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/controller/ConditionRoutesControllerTest.java

`dubbo` condition route only support consumer application , detail #753
XX
XXXX

Fix application scope condition route

---

dubbo-admin-ui/src/components/governance/TagRule.vue

[Enhancement]Tag route search input query application

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/ServiceController.java
dubbo-admin-ui/src/components/governance/AccessControl.vue
dubbo-admin-ui/src/components/governance/RoutingRule.vue
dubbo-admin-ui/src/store/index.js

condition route and accesses query consumer application

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/GenericServiceImpl.java

服务调试bugfix：注册中心使用nacos，并且namespace不是public默认值时，调试找不到服务的问题
服务调试bugfix：注册中心使用nacos，并且namespace不是public默认值时，调试找不到服务的问题
admin.registry.address=nacos://127.0.0.1:8848
admin.config-center=nacos://127.0.0.1:8848
admin.metadata-report.address=nacos://127.0.0.1:8848
admin.registry.namespace=myNamespace
admin.config-center.namespace=myNamespace
admin.metadata-report.namespace=myNamespace
使用服务调试功能

服务调试bugfix：注册中心使用nacos，并且namespace不是public默认值时，调试找不到服务的问题

---

dubbo-admin-ui/src/components/governance/Overrides.vue

Override display serviceVersion and serviceGroup.
XX
XXXX

[BUG]Fix override display serviceVersion and serviceGroup

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/config/impl/ApolloConfiguration.java
dubbo-admin-server/src/main/resources/application.properties
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/config/ConfigCenterTest.java

[ISSUE #771]Use url parameters instead of special configuration

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RegistryServerSync.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/service/RegistryServerSyncTest.java

[ISSUE #778]Fix subscribe service will block admin startup

---

dubbo-admin-ui/src/components/governance/AccessControl.vue
dubbo-admin-ui/src/components/governance/LoadBalance.vue
dubbo-admin-ui/src/components/governance/Overrides.vue
dubbo-admin-ui/src/components/governance/RoutingRule.vue
dubbo-admin-ui/src/components/governance/WeightAdjust.vue

[ISSUE #775]service governance service scope spilt service name

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ConvertUtil.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/RouteUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/Route.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java

blackwhite in condition route

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java

When `admin.config-center` and `admin.metadata-report.address` config Nacos address , Nacos config `public` namespace id is empty , but if `namespace` is empty the default value here is `dubbo` .So remove default config value.
XX
XXXX

Remove default config value

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/YamlParser.java
dubbo-admin-server/src/test/java/org/apache/dubbo/admin/common/util/YamlParserTest.java
dubbo-admin-server/src/test/resources/exploited.yml
pom.xml

Snakeyaml use safe constructor
XX
XXXX

Snakeyaml use safe constructor

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/Tag.java

[ISSUE #784]Fix tag route display addresses bug

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/RouteUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/model/domain/Route.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/RouteServiceImpl.java

[ISSUE #780]Fix assesses can't delete 2.6 version

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java

[ISSUE #786]fix get url from config center

---

dubbo-admin-distribution/src/assembly/source-release.xml

Exclude the".flattened-pom.xml" file into the source package
XX
XXXX

Exclude the".flattened-pom.xml" file into the source package

---

NOTICE
dubbo-admin-distribution/src/NOTICE
dubbo-admin-ui/src/components/public/Footers.vue

Update copyright year

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/ServiceTestV3Util.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
pom.xml

Dubbo 3.0 version init `ReferenceConfig` need `Environment`.
XX
XXXX

Fix generic invoke fail

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/common/util/SyncUtils.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/impl/NacosServiceMapping.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RegistryServerSync.java
dubbo-admin-server/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.admin.registry.mapping.ServiceMapping

[ISSUE #811]Nacos support application discover

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/GenericServiceImpl.java

Fix generic can't invoke repeatedly, Keep`ReferenceConfig` consistent with the ConfigManager cache
```
java.lang.IllegalStateException: Found multiple ReferenceConfigs with unique service name [org.test.apache.dubbo.interfaces.PeopleService], previous: <dubbo:reference async="true" sticky="false" timeout="7000" check="false" generic="true" interface="org.test.apache.dubbo.interfaces.TestService" />, later: <dubbo:reference async="true" timeout="7000" generic="true" interface="org.test.apache.dubbo.interfaces.PeopleService" />. There can only be one instance of ReferenceConfig with the same triple (group, …
```

Fix generic can't invoke repeatedly

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/impl/NacosServiceMapping.java

Reduce nacos mapping service storage
XX
XXXX

Reduce nacos mapping service storage

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/RegistryServerSync.java

optimize some code for RegistryServerSync

Optimize some code for RegistryServerSync

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/AdminMappingListener.java

[ISSUE #821]Fix circular reference

---

dubbo-admin-ui/src/components/governance/Overrides.vue

Fix service version spell
XX
XXXX

Fix service version spell

---

README.md
README_ZH.md

fix format issue in README.md and README_ZH.md, and update npm mirror's url.
Fix README.md
Fix https://github.com/apache/dubbo-admin/issues/856
Preview README.md and README_ZH.md

Fix README.md

---

dubbo-admin-server/pom.xml

support jdk11 #862

---

dubbo-admin-ui/public/index.html

原cdn.bootcss.com域名失效，需要切换到新域名cdn.bootcdn.net
官网申明：https://www.bootcdn.cn
XXXXX
XX
XXXX

fix:#898 Update index.html

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/SwaggerConfiguration.java

support swagger.enable

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/ConfigCenter.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/AdminMappingListener.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/registry/mapping/impl/ZookeeperServiceMapping.java
pom.xml

1. Change `dubbo` version to 3.0.8
2. Change `enable-empty-protection` is false.
3. Adapt to ExtensionLoader
XX
XXXX

Support dubbo 3.0.8

---

dubbo-admin-ui/src/router/index.js

解决重复点功能，浏览器控制台报错问题，如点击：服务查询-搜索按钮

---

dubbo-admin-ui/src/components/ServiceDetail.vue

Update the alignment value

---

dubbo-admin-server/src/main/java/org/apache/dubbo/admin/controller/MetricsCollectController.java
dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java

Fix #734 #585
